### ISSUE TITLE
Cannot validate the experiment for netsim

### ISSUE THREAD

**Issue by ys2899** [loeweX/AmortizedCausalDiscovery#5]
when running 

python -m train --suffix netsim

it will fail at the validation stage:

Traceback (most recent call last):
  File "/Users/bytedance/opt/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/bytedance/opt/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/bytedance/Desktop/total/work/Codebase/Bizops/Causal_Discovery/codebase/train.py", line 238, in <module>
    best_epoch, epoch = train()
  File "/Users/bytedance/Desktop/total/work/Codebase/Bizops/Causal_Discovery/codebase/train.py", line 56, in train
    val_losses = val(epoch)
  File "/Users/bytedance/Desktop/total/work/Codebase/Bizops/Causal_Discovery/codebase/train.py", line 91, in val
    for batch_idx, minibatch in enumerate(valid_loader):
TypeError: 'NoneType' object is not iterable

**Comment by loeweX** [comment]
Hey!

Thanks for your interest in our code. 

I've created and merged a pull request (#6) that should fix this issue. Essentially, since the underlying causal graph in Netsim is the same for all samples, there is no differentiation between train, validation and test set and all results are obtained directly on the training set.
